# Project-wide Gradle settings.

# IDE (e.g. Android Studio) users:
# Gradle settings configured through the IDE will override
# any settings specified in this file.

org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=1024m

android.useAndroidX=true

# Redmi 9 / ARM Android builds only. This avoids unnecessary x86 APK/native artifacts.
reactNativeArchitectures=armeabi-v7a,arm64-v8a

newArchEnabled=true
hermesEnabled=true
edgeToEdgeEnabled=false
